### ISSUE TITLE
`ModuleNotFoundError` when debugging files in workspace subdirectory

### ISSUE THREAD

**Issue by debonte** [microsoft/vscode-python-web-wasm#46]
### `src/declare.py`
```python
def func():
    return "success"
```

### `src/consume.py`
```python
from declare import func

print(func())
```

## Repro Steps

1. Create files as above. Note that they are in the `src` subdirectory of the workspace.
2. Open workspace root (parent of `src`) in `https://insiders.vscode.dev/?vscode-coi=`
3. Open `consume.py`
4. "Run Python File in WASM"
5. Note that "success" is printed in the program output (Terminal pane)
6. "Debug Python File in WASM"
7. When debugger stops at top of file, press the "Continue" button in the debugging toolbar.

## Expected behavior

Code runs successfully again and prints "success" in the program output (Debug Console pane)

## Actual behavior

No "success" in program output. "Debug Console" shows the errors below. I think the "Bad file descriptor" may be a known issue, but note the `ModuleNotFoundError`.

If you move the two files from `src` to the workpace root, the code works as expected while debugging.

On desktop the code works as expected with the files in either location.

```text
PDB debugger connected.
Traceback (most recent call last):
  File "/$debug/main.py", line 12, in run
    dbg._run(tgt)
  File "/lib/python3.11/pdb.py", line 1646, in _run
    self.run(target.code)
  File "/lib/python3.11/bdb.py", line 597, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/workspace/src/consume.py", line 1, in <module>
    from declare import func
ModuleNotFoundError: No module named 'declare'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/$debug/main.py", line 31, in <module>
    run(debugger, target)
  File "/$debug/main.py", line 25, in run
    dbg.interaction(None, t)
  File "/lib/python3.11/pdb.py", line 434, in interaction
    self.print_stack_entry(self.stack[self.curindex])
  File "/lib/python3.11/pdb.py", line 1553, in print_stack_entry
    self.message(prefix +
  File "/lib/python3.11/pdb.py", line 535, in message
    print(msg, file=self.stdout)
OSError: [Errno 8] Bad file descriptor
```

**Comment by dbaeumer** [comment]
@rchiodo can you please investigate

**Comment by rchiodo** [comment]
My suspicion is it's not running the file in the same folder as the file exists in. That would explain the 'ModuleNotFound' error. The bad file descriptor seems like a general problem with exception handling though. I can repro with throwing any exception.

Like maybe stderr cannot be read anymore?
